### ISSUE TITLE
Audio not working correctly

### ISSUE THREAD

**Issue by bundit** [JMPerez/c#17] opened 2019-09-01 18:42 UTC
Hi @JMPerez! I really enjoy the idea of this project so thank you for your work! 

Currently, I am having trouble getting the audio to work at all. I can queue a song and have it "play" which shows the progress bar moving from start to finish. Am I missing something? 

Edit: I have tried running it both locally and on the demo herokuapp.

**Comment by JasonJunJun** [comment] 2019-09-02 00:00
Do you mean you can't hear the audio on the tab?

**Comment by bundit** [comment] 2019-09-02 00:01
Yes exactly. I am accessing the app through chrome

**Comment by JasonJunJun** [comment] 2019-09-02 00:10
Duplicate of #14

**Comment by bundit** [comment] 2019-09-02 00:12
Thanks. Excuse my ignorance

**Closed** 2019-09-02 00:12 UTC
